CREATE TABLE users (
  userId VARCHAR(255) NOT NULL PRIMARY KEY,
  displayName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  photoURL VARCHAR(1000),
  providerId VARCHAR(255)
);

CREATE TABLE notes (
  noteId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userId VARCHAR(255) NOT NULL,
  icon VARCHAR(255),
  title VARCHAR(255) NOT NULL,
  content LONGTEXT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
  updatedAt TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
);